# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_types.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_types.proto',
  package='textmessages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13message_types.proto\x12\x0ctextmessages\"/\n\x0bTextMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\"8\n\x0eSendSmsRequest\x12\x15\n\rclient_number\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"@\n\x0eSendSmsReponse\x12.\n\x0btextMessage\x18\x01 \x01(\x0b\x32\x19.textmessages.TextMessageb\x06proto3'
)




_TEXTMESSAGE = _descriptor.Descriptor(
  name='TextMessage',
  full_name='textmessages.TextMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='textmessages.TextMessage.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='textmessages.TextMessage.message_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=84,
)


_SENDSMSREQUEST = _descriptor.Descriptor(
  name='SendSmsRequest',
  full_name='textmessages.SendSmsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_number', full_name='textmessages.SendSmsRequest.client_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='textmessages.SendSmsRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=142,
)


_SENDSMSREPONSE = _descriptor.Descriptor(
  name='SendSmsReponse',
  full_name='textmessages.SendSmsReponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='textMessage', full_name='textmessages.SendSmsReponse.textMessage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=208,
)

_SENDSMSREPONSE.fields_by_name['textMessage'].message_type = _TEXTMESSAGE
DESCRIPTOR.message_types_by_name['TextMessage'] = _TEXTMESSAGE
DESCRIPTOR.message_types_by_name['SendSmsRequest'] = _SENDSMSREQUEST
DESCRIPTOR.message_types_by_name['SendSmsReponse'] = _SENDSMSREPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextMessage = _reflection.GeneratedProtocolMessageType('TextMessage', (_message.Message,), {
  'DESCRIPTOR' : _TEXTMESSAGE,
  '__module__' : 'message_types_pb2'
  # @@protoc_insertion_point(class_scope:textmessages.TextMessage)
  })
_sym_db.RegisterMessage(TextMessage)

SendSmsRequest = _reflection.GeneratedProtocolMessageType('SendSmsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDSMSREQUEST,
  '__module__' : 'message_types_pb2'
  # @@protoc_insertion_point(class_scope:textmessages.SendSmsRequest)
  })
_sym_db.RegisterMessage(SendSmsRequest)

SendSmsReponse = _reflection.GeneratedProtocolMessageType('SendSmsReponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDSMSREPONSE,
  '__module__' : 'message_types_pb2'
  # @@protoc_insertion_point(class_scope:textmessages.SendSmsReponse)
  })
_sym_db.RegisterMessage(SendSmsReponse)


# @@protoc_insertion_point(module_scope)
