# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smsmessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_types_pb2 as message__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='smsmessage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10smsmessage.proto\x1a\x13message_types.proto2]\n\x0cSMSMessaging\x12M\n\x0bSendMessage\x12\x1c.textmessages.SendSmsRequest\x1a\x1c.textmessages.SendSmsReponse\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[message__types__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SMSMESSAGING = _descriptor.ServiceDescriptor(
  name='SMSMessaging',
  full_name='SMSMessaging',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=41,
  serialized_end=134,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='SMSMessaging.SendMessage',
    index=0,
    containing_service=None,
    input_type=message__types__pb2._SENDSMSREQUEST,
    output_type=message__types__pb2._SENDSMSREPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMSMESSAGING)

DESCRIPTOR.services_by_name['SMSMessaging'] = _SMSMESSAGING

# @@protoc_insertion_point(module_scope)
