# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message_types_pb2 as message__types__pb2


class SMSMessagingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendMessage = channel.unary_stream(
        '/SMSMessaging/SendMessage',
        request_serializer=message__types__pb2.SendSmsRequest.SerializeToString,
        response_deserializer=message__types__pb2.SendSmsReponse.FromString,
        )


class SMSMessagingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SMSMessagingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendMessage': grpc.unary_stream_rpc_method_handler(
          servicer.SendMessage,
          request_deserializer=message__types__pb2.SendSmsRequest.FromString,
          response_serializer=message__types__pb2.SendSmsReponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SMSMessaging', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
