# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import smsmessage_pb2 as smsmessage__pb2


class SMSMessagingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.send_req = channel.unary_unary(
        '/SMSMessaging/send_req',
        request_serializer=smsmessage__pb2.SendSmsRequest.SerializeToString,
        response_deserializer=smsmessage__pb2.SendSmsReponse.FromString,
        )


class SMSMessagingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def send_req(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SMSMessagingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'send_req': grpc.unary_unary_rpc_method_handler(
          servicer.send_req,
          request_deserializer=smsmessage__pb2.SendSmsRequest.FromString,
          response_serializer=smsmessage__pb2.SendSmsReponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SMSMessaging', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
