# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smsmessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smsmessage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10smsmessage.proto\"8\n\x0eSendSmsRequest\x12\x15\n\rclient_number\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x0eSendSmsReponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t2>\n\x0cSMSMessaging\x12.\n\x08send_req\x12\x0f.SendSmsRequest\x1a\x0f.SendSmsReponse\"\x00\x62\x06proto3')
)




_SENDSMSREQUEST = _descriptor.Descriptor(
  name='SendSmsRequest',
  full_name='SendSmsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_number', full_name='SendSmsRequest.client_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='SendSmsRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=76,
)


_SENDSMSREPONSE = _descriptor.Descriptor(
  name='SendSmsReponse',
  full_name='SendSmsReponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_id', full_name='SendSmsReponse.message_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['SendSmsRequest'] = _SENDSMSREQUEST
DESCRIPTOR.message_types_by_name['SendSmsReponse'] = _SENDSMSREPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendSmsRequest = _reflection.GeneratedProtocolMessageType('SendSmsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDSMSREQUEST,
  '__module__' : 'smsmessage_pb2'
  # @@protoc_insertion_point(class_scope:SendSmsRequest)
  })
_sym_db.RegisterMessage(SendSmsRequest)

SendSmsReponse = _reflection.GeneratedProtocolMessageType('SendSmsReponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDSMSREPONSE,
  '__module__' : 'smsmessage_pb2'
  # @@protoc_insertion_point(class_scope:SendSmsReponse)
  })
_sym_db.RegisterMessage(SendSmsReponse)



_SMSMESSAGING = _descriptor.ServiceDescriptor(
  name='SMSMessaging',
  full_name='SMSMessaging',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=116,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_req',
    full_name='SMSMessaging.send_req',
    index=0,
    containing_service=None,
    input_type=_SENDSMSREQUEST,
    output_type=_SENDSMSREPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMSMESSAGING)

DESCRIPTOR.services_by_name['SMSMessaging'] = _SMSMESSAGING

# @@protoc_insertion_point(module_scope)
