# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import delivery_pb2 as delivery__pb2


class UsersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CancelDelivery = channel.unary_unary(
        '/Users/CancelDelivery',
        request_serializer=delivery__pb2.CancelDeliveryRequest.SerializeToString,
        response_deserializer=delivery__pb2.CancelDeliveryResponse.FromString,
        )
    self.RequestDelivery = channel.unary_stream(
        '/Users/RequestDelivery',
        request_serializer=delivery__pb2.RequestDeliveryRequest.SerializeToString,
        response_deserializer=delivery__pb2.RequestDeliveryResponse.FromString,
        )
    self.TrackDelivery = channel.unary_stream(
        '/Users/TrackDelivery',
        request_serializer=delivery__pb2.TrackDeliveryRequest.SerializeToString,
        response_deserializer=delivery__pb2.TrackDeliveryResponse.FromString,
        )


class UsersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CancelDelivery(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestDelivery(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TrackDelivery(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UsersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CancelDelivery': grpc.unary_unary_rpc_method_handler(
          servicer.CancelDelivery,
          request_deserializer=delivery__pb2.CancelDeliveryRequest.FromString,
          response_serializer=delivery__pb2.CancelDeliveryResponse.SerializeToString,
      ),
      'RequestDelivery': grpc.unary_stream_rpc_method_handler(
          servicer.RequestDelivery,
          request_deserializer=delivery__pb2.RequestDeliveryRequest.FromString,
          response_serializer=delivery__pb2.RequestDeliveryResponse.SerializeToString,
      ),
      'TrackDelivery': grpc.unary_stream_rpc_method_handler(
          servicer.TrackDelivery,
          request_deserializer=delivery__pb2.TrackDeliveryRequest.FromString,
          response_serializer=delivery__pb2.TrackDeliveryResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Users', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
